/**:
  ros__parameters:
    # --- PHYSICAL CONFIGURATION (Define ONCE here) ---
    target_depth: 0.20        # Meters (Goal Distance)
    marker_size: 0.05         # Meters (Physical Marker Size)
    smoothing_factor: 0.1     # For depth estimation